exercises/exercise3-rails/config/routes.rb
Rails.application.routes.draw do
  resources 'books'
  get 'static_pages/home'

  root 'static_pages#home'

end

exercises/exercise3-rails/app/models/book.rb
# Books have title, image_url, author, year_published
class Book < ActiveRecord::Base
end

exercises/exercise3-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

exercises/exercise3-rails/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # views always have access to instance vars

  # make the view have access to all books
  def index
    @books = Book.all
  end

  def show
    @book = get_book
    puts "We found book #{@book}"
    puts "rendering show"
    render 'show'
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
    @book = get_book
  end

  def update
    @book = get_book
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy

  end

  private

  # we do this for security - don't let anyone just change anything
  #   only allow specific changes
  def book_params
    params.require(:book).permit(:title,
                                 :year_published,
                                 :author,
                                 :available,
                                 :genre,
                                 :image_url
                                )
  end

  def get_book
    #Book.find(params[:id])
    Book.first
  end
end

exercises/exercise3-rails/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

exercises/exercise3-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

exercises/exercise3-rails/app/helpers/books_helper.rb
module BooksHelper
end

exercises/exercise3-rails/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

exercises/exercise3-rails/app/views/books/edit.html.erb
<div class="col-xs-12">
  <h1 style="color:#cc3333;">Edit book</h1>
  <div class='well'>

    <%= simple_form_for @book do |f| %>
      <%= f.input :title %>
      <%= f.input :author %>
      <%= f.input :genre %>
      <%= f.input :image_url %>
      <%= f.submit "Submit".html_safe, class: 'btn btn-lg btn-danger' %>
    <% end %>
  </div>
</div>

exercises/exercise3-rails/app/views/books/index.html.erb
<div class="col-12">
  <h1>Our Book Collection</h1>

  <div class="well">
    <% @books.each do |book| %>
      <ul>
        <li><%= link_to book.title, book%></li>
      </ul>
    <% end %>
  </div>
</>

<div class="well">
  <%= link_to "Add NewBook", new_book_path, class: 'btn btn-defaults' %>
</div>

exercises/exercise3-rails/app/views/books/new.html.erb
<div class="col-xs-12">
  <h1 style="color:#cc3333;">New book</h1>
  <div class='well'>

    <%= simple_form_for @book do |f| %>
      <%= f.input :title %>
      <%= f.input :author %>
      <%= f.input :genre %>
      <%= f.input :image_url %>
      <%= f.submit "Submit".html_safe, class: 'btn btn-lg btn-danger' %>
    <% end %>
  </div>
</div>

exercises/exercise3-rails/app/views/books/show.html.erb
<div class="col-xs-12">
  <div class="row-fluid">
    <h1><%= @book.title %></h1>
    <ul><%= @book.author %></ul>
    <ul><%= image_tag(@book.image_url, class: 'img-thumbnail img-responsive') %> </ul>
  </div>

  <div class="row-fluid">
    <%= link_to "All Books", books_path, class: 'btn btn-lg btn-primary' %>
    <%= link_to 'Edit This Book', edit_book_path(@book), class: 'btn btn-lg btn-warning' %>
  </div>

</div>

exercises/exercise3-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookazonApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

exercises/exercise3-rails/app/views/static_pages/home.html.erb
<h1>Welcome to bookazon</h1>
<p> the best place for cool books</p>
<%= link_to 'checkout our books', books_path, class: 'btn btn-lg btn-danger' %>